More cost-efficient deployment

diff --git a/back/deployment/prisma/Dockerfile b/back/deployment/prisma/Dockerfile
--- a/back/deployment/prisma/Dockerfile
+++ b/back/deployment/prisma/Dockerfile
@@ -1,6 +1,12 @@
 FROM prismagraphql/prisma:1.32
-ENV PRISMA_CONFIG_PATH prisma.yml
-COPY deployment/prisma/config.yml config.yml
-COPY deployment/prisma/sub.sh sub.sh
-ENTRYPOINT sh sub.sh && sh -c /app/start.sh
+
+RUN apk add curl
+
+ARG PRISMA_CONFIG
+ENV PRISMA_CONFIG=$PRISMA_CONFIG
+
+RUN if [ -z "$PRISMA_CONFIG" ]; then echo "Missing required arg PRISMA_CONFIG"; exit 1; fi
+
+ENTRYPOINT sh -c /app/start.sh
+
 EXPOSE 4466
